### ISSUE TITLE
Dataframe don't have fold

### ISSUE THREAD

**Issue by faslurrajah** [Kaushal28/Global-Wheat-Detection#1]
```
class WheatDataset(Dataset):
    
    def __init__(self, df, folds, transforms=None):
        self.df = df[df.kfold.isin(folds)].reset_index(drop=True)
        self.image_ids = self.df['image_id'].unique()
        self.transforms = transforms

```

Here you coded as `df[df.kfold.isin(folds)].reset_index(drop=True)` . But df is a dataframe. So it's throwing an exception. Am I missing anything?

**Comment by Kaushal28** [comment]
@faslurrajah, Yes `df` is a dataframe and `kfold` is its column.

**Comment by faslurrajah** [comment]
Oh. Is it possible to share the train.csv file which contains kfold column? I'm just trying to understand your kfold logic using the wheat dataset?

**Comment by faslurrajah** [comment]
or can you let me know the idea behind kfold column in train.csv file

**Comment by Kaushal28** [comment]
Refer this: https://www.kaggle.com/kaushal2896/gwd-dataset-splitter. I've created similar dataframe and splits there.
